// <auto-generated />
using System;
using EasyOrder.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EasyOrder.Data.Migrations
{
    [DbContext(typeof(EasyOrderContext))]
    [Migration("20211119184533_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.HasSequence<int>("NumberOrder")
                .HasMin(1L);

            modelBuilder.HasSequence<int>("ProductCode")
                .HasMin(1L);

            modelBuilder.Entity("EasyOrder.Business.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.CategoryExtra", b =>
                {
                    b.Property<Guid>("IdCategory")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdExtra")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdCategory", "IdExtra");

                    b.HasIndex("IdExtra");

                    b.ToTable("CategoryExtras");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.Extra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Extras");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdOrder")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProduct")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observation")
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdOrder");

                    b.HasIndex("IdProduct");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.ItemExtra", b =>
                {
                    b.Property<Guid>("IdItem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdExtra")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdItem", "IdExtra");

                    b.HasIndex("IdExtra");

                    b.ToTable("ItemExtras");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR NumberOrder");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Table")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR ProductCode");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("IdCategory")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.CategoryExtra", b =>
                {
                    b.HasOne("EasyOrder.Business.Models.Category", "Category")
                        .WithMany("CategoryExtras")
                        .HasForeignKey("IdCategory")
                        .IsRequired();

                    b.HasOne("EasyOrder.Business.Models.Extra", "Extra")
                        .WithMany("CategoryExtras")
                        .HasForeignKey("IdExtra")
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Extra");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.Item", b =>
                {
                    b.HasOne("EasyOrder.Business.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyOrder.Business.Models.Product", "Product")
                        .WithMany("Items")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.ItemExtra", b =>
                {
                    b.HasOne("EasyOrder.Business.Models.Extra", "Extra")
                        .WithMany()
                        .HasForeignKey("IdExtra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyOrder.Business.Models.Item", "Item")
                        .WithMany("ItemExtras")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extra");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.Product", b =>
                {
                    b.HasOne("EasyOrder.Business.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("IdCategory")
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.Category", b =>
                {
                    b.Navigation("CategoryExtras");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.Extra", b =>
                {
                    b.Navigation("CategoryExtras");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.Item", b =>
                {
                    b.Navigation("ItemExtras");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EasyOrder.Business.Models.Product", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
